android: implement app split tunneling support
tailscale/tailscale-android pull request #435
Opened 2024-06-26 18:47 UTC by agottardo

<img width="300" src="https://github.com/tailscale/tailscale-android/assets/9057073/65fd9eb4-e54b-4e45-9079-af69ff36fa70" align="right" />

Updates tailscale/tailscale#6912

This PR is a little QoL improvement for our Android users. It adds UI and models that provide the ability to add/remove apps which should be excluded from going through the VPN tunnel.

### To-dos

- [ ] Test the interaction between this and the hardcoded list of excluded apps we already have
- [ ] Implement logic to update the VPN settings while the app is running (currently, this PR requires you to disconnect and reconnect the tunnel to apply any exclusion choices).
- [ ] Determine Play Store follow-up work as the `QUERY_ALL_PACKAGES` permission was needed to be added here

2024-07-02 16:46 UTC, Killdev33 requested changes
Delete not me

2024-07-02 16:47 UTC, Killdev33 requested changes
Delete

2024-07-02 16:47 UTC, Killdev33 requested changes
Delete

2024-07-02 16:48 UTC, Killdev33 requested changes
Delete

2024-07-02 16:48 UTC, Killdev33 requested changes
Delete plz

2024-07-02 16:48 UTC, Killdev33 requested changes
Delete

2024-07-02 16:49 UTC, Killdev33 requested changes
Delete

2024-07-02 16:49 UTC, Killdev33 requested changes
Delete

2024-07-02 16:50 UTC, Killdev33 requested changes
Delete

2024-07-02 16:50 UTC, Killdev33 requested changes
Delete

2024-07-03 18:43 UTC, barnstar approved these changes

2024-07-03 20:43 UTC, merged

2024-07-07 22:43 UTC, agottardo commented
> Split tunnel should be have ability to manage by admin.

That's being worked on. If you have concerns in the future about upcoming features, please open an actual issue as old pull requests are not monitored for new comments.