android: stop tailscaled when VPN has been revoked
tailscale/tailscale-android pull request #480
Opened 2024-08-26 22:42 UTC by kari-ts

-add new Ipn UI state 'Stopping' to handle the case where the VPN is no longer active and a request to stop Tailscale has been issued (but is not complete yet) and use for optimistic UI -when VPN has been revoked, stop tailscaled and set the state to Stopping -this fixes the race condition where when we tell tailscaled to stop, stopping races against the netmap state updating as a result of the VPN being revoked -add isActive state and use instead of isPrepared for UI showing whether we are connected - we were previously using isPrepared as a proxy for connection, but sometimes the VPN has been prepared but is not active (eg when VPN permissions have been given and VPN has been connected previously, but has been revoked) -refactor network callbacks into its own class for readability

Fixes tailscale/tailscale#12850

2024-08-27 00:01 UTC, agottardo commented on android/src/main/java/com/tailscale/ipn/ui/viewModel/VpnViewModel.kt
>    // Whether the VPN is prepared
Can we provide comments to explain the difference between `vpnPrepared` and `vpnActive`, and their purpose? Who sets these, and who reads them?

2024-08-27 00:02 UTC, agottardo commented on libtailscale/net.go
> +		fmt.Printf("updateTUN: no change to Routes or DNS, ignore")
did you mean to drop the logger?

2024-08-27 00:02 UTC, agottardo commented on libtailscale/net.go
> +	log.Printf("KARI, setting vpn status to true")
debugging leftover

2024-08-27 00:02 UTC, agottardo commented on libtailscale/net.go
> +	log.Printf("KARI, setting vpn status to true")
no harm in leaving it, just drop the Kari part

2024-08-27 00:03 UTC, agottardo requested changes
Some nits

2024-08-27 03:33 UTC, kari-ts commented on libtailscale/net.go
> +		fmt.Printf("updateTUN: no change to Routes or DNS, ignore")
reverting change!

2024-08-28 16:25 UTC, agottardo commented on android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
> +import android.util.Log
unused import?

2024-08-28 16:28 UTC, agottardo commented on android/src/main/java/com/tailscale/ipn/App.kt
> +  fun getAppsScopedViewModel(): VpnViewModel {
```suggestion
  fun getAppScopedViewModel(): VpnViewModel {
```

2024-08-28 16:29 UTC, agottardo approved these changes

2024-08-28 16:45 UTC, merged